version: '3.9'

services:
  backend:
    build: .
    container_name: quotable-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: quotable-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
